---
abstract: 'A fast, portable and efficient library based on Lorcon2. Written in XS for perl penetration tester and wireless-security experts'
author:
  - 'Edoardo Mantovani, aka BASEBAND <BASEBAND_at_cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Air-Lorcon2
no_index:
  directory:
    - t
    - inc
requires:
  Net::MAC: '0'
  Net::Pcap: '0'
  strict: '0'
  Data::Dumper: '0'
  perl: '5.22.1'
version: '26.01'
